
const dataExample = {
    "status": {
        "timestamp": "2021-11-13T15:28:20.404Z",
        "error_code": 0,
        "error_message": null,
        "elapsed": 23,
        "credit_count": 1,
        "notice": null
    },
    "data": {
        "BTC": {
            "id": 1,
            "name": "Bitcoin",
            "symbol": "BTC",
            "slug": "bitcoin",
            "num_market_pairs": 8304,
            "date_added": "2013-04-28T00:00:00.000Z",
            "tags": [
                "mineable",
                "pow",
                "sha-256",
                "store-of-value",
                "state-channel",
                "coinbase-ventures-portfolio",
                "three-arrows-capital-portfolio",
                "polychain-capital-portfolio",
                "binance-labs-portfolio",
                "blockchain-capital-portfolio",
                "boostvc-portfolio",
                "cms-holdings-portfolio",
                "dcg-portfolio",
                "dragonfly-capital-portfolio",
                "electric-capital-portfolio",
                "fabric-ventures-portfolio",
                "framework-ventures-portfolio",
                "galaxy-digital-portfolio",
                "huobi-capital-portfolio",
                "alameda-research-portfolio",
                "a16z-portfolio",
                "1confirmation-portfolio",
                "winklevoss-capital-portfolio",
                "usv-portfolio",
                "placeholder-ventures-portfolio",
                "pantera-capital-portfolio",
                "multicoin-capital-portfolio",
                "paradigm-portfolio"
            ],
            "max_supply": 21000000,
            "circulating_supply": 18872068,
            "total_supply": 18872068,
            "is_active": 1,
            "platform": null,
            "cmc_rank": 1,
            "is_fiat": 0,
            "last_updated": "2021-11-13T15:27:02.000Z",
            "quote": {
                "2790": {
                    "price": 56450.71158765501,
                    "volume_24h": 27554017336.884045,
                    "volume_change_24h": -14.4556,
                    "percent_change_1h": 0.15144044,
                    "percent_change_24h": 1.33953105,
                    "percent_change_7d": 4.69298927,
                    "percent_change_30d": 11.82917082,
                    "percent_change_60d": 37.88572741,
                    "percent_change_90d": 40.40342388,
                    "market_cap": 1065341667730.6133,
                    "market_cap_dominance": 43.075,
                    "fully_diluted_market_cap": 1185464943340.7515,
                    "last_updated": "2021-11-13T15:27:39.000Z"
                }
            }
        },
        "ETH": {
            "id": 1027,
            "name": "Ethereum",
            "symbol": "ETH",
            "slug": "ethereum",
            "num_market_pairs": 4532,
            "date_added": "2015-08-07T00:00:00.000Z",
            "tags": [
                "mineable",
                "pow",
                "smart-contracts",
                "ethereum-ecosystem",
                "binance-smart-chain",
                "coinbase-ventures-portfolio",
                "three-arrows-capital-portfolio",
                "polychain-capital-portfolio",
                "binance-labs-portfolio",
                "blockchain-capital-portfolio",
                "boostvc-portfolio",
                "cms-holdings-portfolio",
                "dcg-portfolio",
                "dragonfly-capital-portfolio",
                "electric-capital-portfolio",
                "fabric-ventures-portfolio",
                "framework-ventures-portfolio",
                "hashkey-capital-portfolio",
                "kinetic-capital",
                "huobi-capital-portfolio",
                "alameda-research-portfolio",
                "a16z-portfolio",
                "1confirmation-portfolio",
                "winklevoss-capital-portfolio",
                "usv-portfolio",
                "placeholder-ventures-portfolio",
                "pantera-capital-portfolio",
                "multicoin-capital-portfolio",
                "paradigm-portfolio"
            ],
            "max_supply": null,
            "circulating_supply": 118325845.749,
            "total_supply": 118325845.749,
            "is_active": 1,
            "platform": null,
            "cmc_rank": 2,
            "is_fiat": 0,
            "last_updated": "2021-11-13T15:27:03.000Z",
            "quote": {
                "2790": {
                    "price": 4080.576749264576,
                    "volume_24h": 13332243776.96773,
                    "volume_change_24h": -21.1449,
                    "percent_change_1h": -0.210909,
                    "percent_change_24h": 1.12934713,
                    "percent_change_7d": 4.39222913,
                    "percent_change_30d": 22.35987417,
                    "percent_change_60d": 37.59550431,
                    "percent_change_90d": 48.04064527,
                    "market_cap": 482837695000.43604,
                    "market_cap_dominance": 19.5078,
                    "fully_diluted_market_cap": 482837695000.4368,
                    "last_updated": "2021-11-13T15:27:39.000Z"
                }
            }
        }
    }
  };

export default dataExample;